name: Pembersihan Firebase Harian

on:
  schedule:
    # Jam 22:00 UTC sama dengan Jam 05:00 WIB
    - cron: '0 22 * * *'
  workflow_dispatch: # Agar Anda bisa mencoba hapus manual dari tombol di GitHub

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Menghapus Data Realtime Database Semua Node
        run: |
          # Perintah untuk menghapus folder data_web (Dashboard Node 1 - 4)
          curl -X DELETE "https://projectsiswa-d4c27-default-rtdb.asia-southeast1.firebasedatabase.app/data_web.json"
          curl -X DELETE "https://projectsiswa-d4c27-default-rtdb.asia-southeast1.firebasedatabase.app/data_web2.json"
          curl -X DELETE "https://projectsiswa-d4c27-default-rtdb.asia-southeast1.firebasedatabase.app/data_web3.json"
          curl -X DELETE "https://projectsiswa-d4c27-default-rtdb.asia-southeast1.firebasedatabase.app/data_web4.json"
          
          echo "Pembersihan Data Live Cloud (4 Node) Berhasil!"
